version: 2.1
workflows:
  load_test:
    jobs:
      - run-k6-test
jobs:
  run-k6-test:
    docker:
      - image: loadimpact/k6:latest
    steps:
      - checkout
      - run:
          name: Run k6 test
          command: k6 run todos-testing.js
