# snippet from .circleci/config.yml configuration file 
version: 2.1
orbs:
 k6io: k6io/test@1.1.0
workflows:
 load_test:
   jobs:
     - k6io/test:
         script: todos-testing.js
     - k6io/test:
         script: scenario-tests/todos-development-tests.js
     - k6io/test:
         script: scenario-tests/todos-development-tests.js 
